# Project information
site_name: MkDocs using Read the Docs
site_description: Built with MkDocs using a theme provided by Read the Docs.
site_author: Sogrey
site_url: https://Sogrey.github.io/MKDocs-ReadTheDocs/

# Repository
repo_name: Sogrey/MKDocs-ReadTheDocs
repo_url: https://github.com/Sogrey/MKDocs-ReadTheDocs

# Copyright
copyright: Copyright &copy; 2016 - 2024 Sogrey

# Configuration
theme:
  name: readthedocs
  language: en
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
    
nav:
    - Home: index.md
    - ReadTheDocs: ReadTheDocs.md
    - About: about.md

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Sogrey/MKDocs-ReadTheDocs
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/squidfunk
    # - icon: fontawesome/brands/linkedin
    #   link: https://linkedin.com/in/squidfunk

# Google Analytics
# google_analytics:
#   - UA-XXXXXXXX-X
#   - auto

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true